[airlock_hec_routing_exechistories]
REGEX = \"execution_type\"\s*:\s*
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::airlock:exechistories

[airlock_hec_routing_agent]
REGEX = \"agentid\"\s*:\s*
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::airlock:agent

[airlock_hec_routing_svractivities]
REGEX = \"task\"\s*:\s*
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::airlock:svractivities

[airlock_hec_routing_policies]
REGEX = \"auditmode\"\s*:\s*
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::airlock:policies
