# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 10

[launcher]
author = AirlockDigital
version = 6.0.0
description = Ingests Agent, File Execution and Server Activity History logs from an Airlock Digital server via the rest API.

[ui]
is_visible = 1
label = Airlock Digital Add-On
docs_section_override = AddOns:released

[package]
id = TA-airlock-digital-rest-api-logger-cloud

[triggers]
reload.addon_builder = simple
reload.ta_airlock_digital_rest_api_logger_cloud_account = simple
reload.ta_airlock_digital_rest_api_logger_cloud_settings = simple
reload.passwords = simple

