[airlock_policies]
start_by_shell = false
python.version = python3
sourcetype = airlock:policies
interval = 86400
disabled = 0

[airlock_agent]
start_by_shell = false
python.version = python3
sourcetype = airlock:agent
interval = 86400
disabled = 0

[airlock_execution_history]
start_by_shell = false
python.version = python3
sourcetype = airlock:exechistories
interval = 60
execution_types_to_collect = ['0', '10', '2', '3', '4', '5', '6', '7', '8', '9', '1', '11', '12', '13', '14', '15', '16', '17', '18']
delete_existing_checkpoint = False
disabled = 0

[airlock_server_activities]
start_by_shell = false
python.version = python3
sourcetype = airlock:svractivities
interval = 60
delete_existing_checkpoint = False
disabled = 0


[airlock_otp_usage]
start_by_shell = false
python.version = python3
sourcetype = airlock:otpusage
interval = 300
delete_existing_checkpoint = False
disabled = 0
