[airlock:agent]
KV_MODE = json
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[airlock:exechistories]
KV_MODE = json
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[airlock:hec]
TRANSFORMS-sourcetype = airlockexe, airlocksrv

[airlock:policies]
KV_MODE = json
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[airlock:svractivities]
KV_MODE = json
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[source::...ta-airlock-digital-rest-api-logger-cloud*.log*]
sourcetype = taairlockdigitalrestapiloggercloud:log

[source::...ta_airlock_digital_rest_api_logger_cloud*.log*]
sourcetype = taairlockdigitalrestapiloggercloud:log