
[admin:TA_airlock_digital_rest_api_logger_cloud]
match = /
members = TA_airlock_digital_rest_api_logger_cloud_settings, TA_airlock_digital_rest_api_logger_cloud_airlock_policies, TA_airlock_digital_rest_api_logger_cloud_airlock_agent, TA_airlock_digital_rest_api_logger_cloud_airlock_execution_history, TA_airlock_digital_rest_api_logger_cloud_airlock_server_activities, TA_airlock_digital_rest_api_logger_cloud_airlock_otp_usage

[admin_external:TA_airlock_digital_rest_api_logger_cloud_settings]
handlertype = python
python.version = python3
handlerfile = TA_airlock_digital_rest_api_logger_cloud_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_airlock_digital_rest_api_logger_cloud_airlock_policies]
handlertype = python
python.version = python3
handlerfile = TA_airlock_digital_rest_api_logger_cloud_rh_airlock_policies.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_airlock_digital_rest_api_logger_cloud_airlock_agent]
handlertype = python
python.version = python3
handlerfile = TA_airlock_digital_rest_api_logger_cloud_rh_airlock_agent.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_airlock_digital_rest_api_logger_cloud_airlock_execution_history]
handlertype = python
python.version = python3
handlerfile = TA_airlock_digital_rest_api_logger_cloud_rh_airlock_execution_history.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_airlock_digital_rest_api_logger_cloud_airlock_server_activities]
handlertype = python
python.version = python3
handlerfile = TA_airlock_digital_rest_api_logger_cloud_rh_airlock_server_activities.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_airlock_digital_rest_api_logger_cloud_airlock_otp_usage]
handlertype = python
python.version = python3
handlerfile = TA_airlock_digital_rest_api_logger_cloud_rh_airlock_otp_usage.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
