[proxy]
proxy_enabled = 
proxy_type = http
proxy_url = 
proxy_port = 
proxy_username = 
proxy_password = 
proxy_rdns = 

[logging]
loglevel = INFO

[additional_parameters]
airlock_server_url = 
airlock_rest_api_key = 
airlock_directory_id = 
airlock_tenant_id = 
airlock_rest_api_port = 

