[airlockexe]
DEST_KEY = MetaData:Sourcetype
REGEX = FileActivityMessage
FORMAT = sourcetype::airlock:exechistories

[airlocksrv]
DEST_KEY = MetaData:Sourcetype
REGEX = ServerActivityMessage
FORMAT = sourcetype::airlock:svractivities
