
[expose:TA_airlock_digital_rest_api_logger_cloud_settings]
pattern = TA_airlock_digital_rest_api_logger_cloud_settings
methods = POST, GET

[expose:TA_airlock_digital_rest_api_logger_cloud_settings_specified]
pattern = TA_airlock_digital_rest_api_logger_cloud_settings/*
methods = POST, GET, DELETE

[expose:TA_airlock_digital_rest_api_logger_cloud_airlock_policies]
pattern = TA_airlock_digital_rest_api_logger_cloud_airlock_policies
methods = POST, GET

[expose:TA_airlock_digital_rest_api_logger_cloud_airlock_policies_specified]
pattern = TA_airlock_digital_rest_api_logger_cloud_airlock_policies/*
methods = POST, GET, DELETE

[expose:TA_airlock_digital_rest_api_logger_cloud_airlock_agent]
pattern = TA_airlock_digital_rest_api_logger_cloud_airlock_agent
methods = POST, GET

[expose:TA_airlock_digital_rest_api_logger_cloud_airlock_agent_specified]
pattern = TA_airlock_digital_rest_api_logger_cloud_airlock_agent/*
methods = POST, GET, DELETE

[expose:TA_airlock_digital_rest_api_logger_cloud_airlock_execution_history]
pattern = TA_airlock_digital_rest_api_logger_cloud_airlock_execution_history
methods = POST, GET

[expose:TA_airlock_digital_rest_api_logger_cloud_airlock_execution_history_specified]
pattern = TA_airlock_digital_rest_api_logger_cloud_airlock_execution_history/*
methods = POST, GET, DELETE

[expose:TA_airlock_digital_rest_api_logger_cloud_airlock_server_activities]
pattern = TA_airlock_digital_rest_api_logger_cloud_airlock_server_activities
methods = POST, GET

[expose:TA_airlock_digital_rest_api_logger_cloud_airlock_server_activities_specified]
pattern = TA_airlock_digital_rest_api_logger_cloud_airlock_server_activities/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
